import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import web from "../public/webdev.png";
import app from "../public/appdev.png";
import Image from "next/image";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">

        <section className="min-h-screen">

          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Orbin</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>


          <div className="text-center p-10 py-10">

            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Orbin Sunny
            </h2>

            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Mobile App And Website Dev
            </h3>

            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" alt={""} />
            </div>

          </div>

        </section>


        <section>

          <div>

            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a computer science student and sort of in the learning process.
              
            </p>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer services for website developing and app developing using react, flutter, next, etc...
            </p>

          </div>

          <div className="lg:flex gap-10">

            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className='mx-auto' src={web} width={100} height={100} alt={""} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
               Beautiful Websites
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your website following.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Next</p>
              
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image className='mx-auto' src={app} width={100} height={100} alt={""} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                App Development
              </h3>
              <p className="py-2">
                Making designs into finished apps.
              </p>
              <h4 className="py-4 text-teal-600">Platforms I Use</h4>
              <p className="text-gray-800 py-1">Flutter</p>
           
            </div>

          </div>

        </section>


        <section className="py-10">

          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              {/* <Image
                className="rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
             
                alt="" */}
              {/* /> */}
            </div>
          
            
            
          </div>

        </section>

      </main>
    </div>
  );
}